name: "CI"
on: [push]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Execute action
        uses: ./

      - name: Run tests against Azurite
        run: yarn test