on: [push]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world action step
        uses: ./
        id: hello
        
      # TODO: Use curl to verify azurite is running